import type { Recipe } from "@/lib/types";

const NOW = "2026-08-01T00:00:00.000Z";

function ing(id: string, en: string, vi: string, qty: number, unit: string) {
  return { id, name: { en, vi }, qty, unit };
}

function step(id: string, en: string, vi: string) {
  return { id, text: { en, vi } };
}

export const SEED_RECIPES: Recipe[] = [
  {
    id: "rc_jerk_chicken",
    name: { en: "Jerk Chicken Meal", vi: "Gà Jerk" },
    category: "main",
    basePortions: 12,
    ingredients: [
      ing("i1", "Chicken leg quarters", "Đùi gà nguyên", 12, "pcs"),
      ing("i2", "Jerk marinade", "Sốt ướp Jerk", 1, "batch (confidential — ask Head Chef)"),
      ing("i3", "Rice and Peas", "Cơm đậu", 12, "portion"),
      ing("i4", "Steamed Veg", "Rau củ hấp", 12, "portion"),
      ing("i5", "Plantain", "Chuối chiên", 12, "portion"),
    ],
    steps: [
      step("s1", "Marinate chicken in Jerk marinade — minimum 24h.", "Ướp gà với sốt Jerk — tối thiểu 24 giờ."),
      step("s2", "Bring chicken to room temp 20 min before grilling.", "Để gà ở nhiệt độ phòng 20 phút trước khi nướng."),
      step("s3", "Grill over charcoal, turning regularly, until core temp ≥75°C.", "Nướng trên than hoa, lật đều tay, đến khi nhiệt độ lõi ≥75°C."),
      step("s4", "Rest 5 minutes, then plate with Rice and Peas, Steamed Veg and Plantain.", "Để nghỉ 5 phút, sau đó bày cùng Cơm đậu, Rau củ hấp và Chuối chiên."),
    ],
    notes: {
      en: "Jerk marinade recipe is confidential and intentionally not listed here — Head Chef only, per standing kitchen rule.",
      vi: "Công thức sốt ướp Jerk là bí mật và cố tình không liệt kê ở đây — chỉ Bếp trưởng biết, theo quy định bếp.",
    },
    updatedAt: NOW,
  },
  {
    id: "rc_rice_peas",
    name: { en: "Rice and Peas", vi: "Cơm Đậu" },
    category: "side",
    basePortions: 36,
    ingredients: [
      ing("i1", "Kidney beans, canned (whole cans, not drained)", "Đậu đỏ đóng hộp (nguyên hộp, không để ráo)", 1600, "g (4 cans)"),
      ing("i2", "Coconut milk", "Nước cốt dừa", 880, "ml (2×440ml cans)"),
      ing("i3", "Water", "Nước", 800, "ml"),
      ing("i4", "Long grain rice", "Gạo tẻ hạt dài", 2000, "g"),
      ing("i5", "Sea salt", "Muối biển", 36, "g"),
      ing("i6", "Scallion", "Hành lá", 120, "g"),
      ing("i7", "Garlic", "Tỏi", 24, "g"),
      ing("i8", "Pimento / allspice", "Bột đa hương (pimento)", 16, "g"),
      ing("i9", "Thyme", "Lá xạ hương (thyme)", 12, "g"),
    ],
    steps: [
      step("s1", "Combine everything in a pot.", "Cho tất cả nguyên liệu vào nồi."),
      step("s2", "Bring to the boil, then simmer 15 min on medium heat.", "Đun sôi, sau đó hầm 15 phút ở lửa vừa."),
      step("s3", "Simmer a further 5–10 min on low heat.", "Hầm thêm 5–10 phút ở lửa nhỏ."),
      step("s4", "Rest 10 minutes, covered, before serving.", "Để nghỉ 10 phút, đậy nắp, trước khi phục vụ."),
    ],
    costPerPortionVnd: 7358,
    notes: { en: "150g portion. This is a real batch — scales from 36 portions, not 12.", vi: "Khẩu phần 150g. Đây là mẻ thật — nhân từ 36 khẩu phần, không phải 12." },
    updatedAt: NOW,
  },
  {
    id: "rc_steamed_veg",
    name: { en: "Steamed Veg", vi: "Rau Củ Hấp" },
    category: "side",
    basePortions: 12,
    ingredients: [
      ing("i1", "Oil", "Dầu ăn", 30, "ml"),
      ing("i2", "Onion", "Hành tây", 70, "g"),
      ing("i3", "Garlic", "Tỏi", 15, "g"),
      ing("i4", "Thyme", "Lá xạ hương (thyme)", 6, "g"),
      ing("i5", "White cabbage", "Bắp cải trắng", 250, "g"),
      ing("i6", "Carrot", "Cà rốt", 250, "g"),
      ing("i7", "Red pepper", "Ớt chuông đỏ", 300, "g"),
      ing("i8", "Water", "Nước", 60, "ml"),
      ing("i9", "All-purpose seasoning", "Gia vị tổng hợp", 5, "g"),
      ing("i10", "Black pepper", "Tiêu đen", 3, "g"),
      ing("i11", "Salt", "Muối", 9, "g"),
    ],
    steps: [
      step("s1", "Sweat onion, garlic and thyme in oil.", "Phi hành tây, tỏi và thyme với dầu."),
      step("s2", "Add cabbage, carrot and red pepper.", "Cho bắp cải, cà rốt và ớt chuông đỏ vào."),
      step("s3", "Add water, cover and steam until just tender.", "Thêm nước, đậy nắp và hấp đến khi vừa chín tới."),
      step("s4", "Season with all-purpose seasoning, black pepper and salt.", "Nêm gia vị tổng hợp, tiêu đen và muối."),
    ],
    updatedAt: NOW,
  },
  {
    id: "rc_plantain",
    name: { en: "Plantain", vi: "Chuối Chiên" },
    category: "side",
    basePortions: 12,
    ingredients: [ing("i1", "Plantain (chuối già, Kamereo A375)", "Chuối già (Kamereo A375)", 6, "whole (~180g each)")],
    steps: [
      step("s1", "Peel plantains.", "Gọt vỏ chuối."),
      step("s2", "Cut into 8 pieces each.", "Cắt mỗi quả thành 8 miếng."),
      step("s3", "Shallow fry until golden.", "Chiên ngập một nửa đến khi vàng."),
    ],
    costPerPortionVnd: 1890,
    notes: { en: "1 portion = 4 pieces. Bundled into the Jerk Chicken Meal, not a standalone side.", vi: "1 khẩu phần = 4 miếng. Đi kèm trong Gà Jerk, không bán riêng." },
    updatedAt: NOW,
  },
  {
    id: "rc_fried_dumplings",
    name: { en: "Fried Dumplings", vi: "Bánh Bột Chiên" },
    category: "side",
    basePortions: 12,
    ingredients: [
      ing("i1", "All-purpose flour", "Bột mì đa dụng", 290, "g"),
      ing("i2", "Baking powder", "Bột nở", 17, "g"),
      ing("i3", "Sea salt", "Muối biển", 5.9, "g"),
      ing("i4", "Granulated sugar", "Đường trắng", 24, "g"),
      ing("i5", "Vegan butter", "Bơ thực vật", 69, "g"),
      ing("i6", "Warm water", "Nước ấm", 194, "g"),
    ],
    steps: [
      step("s1", "Mix dry ingredients, rub in butter, bring together with warm water.", "Trộn nguyên liệu khô, bóp bơ vào, nhồi cùng nước ấm."),
      step("s2", "Divide into 12 pieces (50g each).", "Chia thành 12 phần (mỗi phần 50g)."),
      step("s3", "Check fryer ready-light (green on, red off) before frying.", "Kiểm tra đèn báo chảo chiên (xanh sáng, đỏ tắt) trước khi chiên."),
      step("s4", "Fry at 170°C, ~6–8 minutes.", "Chiên ở 170°C, khoảng 6–8 phút."),
    ],
    costPerPortionVnd: 2501,
    notes: { en: "Cost is per piece (12 pieces, 50g each).", vi: "Giá tính theo miếng (12 miếng, mỗi miếng 50g)." },
    updatedAt: NOW,
  },
  {
    id: "rc_mac_cheese",
    name: { en: "Mac and Cheese", vi: "Mì Ống Phô Mai" },
    category: "side",
    basePortions: 10,
    ingredients: [
      ing("i1", "Milk", "Sữa tươi", 355, "ml"),
      ing("i2", "Cream", "Kem tươi", 240, "ml"),
      ing("i3", "Macaroni", "Nui ống (macaroni)", 454, "g"),
      ing("i4", "Cheddar", "Phô mai Cheddar", 440, "g"),
      ing("i5", "Parmesan", "Phô mai Parmesan", 100, "g"),
      ing("i6", "Butter", "Bơ", 100, "g"),
      ing("i7", "Salt", "Muối", 6, "g"),
      ing("i8", "Black pepper", "Tiêu đen", 2.4, "g"),
    ],
    steps: [
      step("s1", "Cook macaroni until just al dente.", "Luộc nui đến khi vừa chín tới."),
      step("s2", "Warm milk and cream, melt in butter, cheddar and parmesan.", "Đun ấm sữa và kem, cho bơ, cheddar và parmesan vào tan chảy."),
      step("s3", "Combine with macaroni, season with salt and black pepper.", "Trộn với nui, nêm muối và tiêu đen."),
    ],
    costPerPortionVnd: 27601,
    notes: { en: "~55% food cost — accepted as-is, cheese is genuinely expensive with no fix available without changing the dish.", vi: "Chi phí nguyên liệu ~55% — chấp nhận vì phô mai vốn đắt, không có cách giảm nếu không đổi công thức." },
    updatedAt: NOW,
  },
  {
    id: "rc_house_salad",
    name: { en: "House Salad", vi: "Salad Nhà Làm" },
    category: "side",
    basePortions: 10,
    ingredients: [
      ing("i1", "Cucumber, cherry tomato, red onion mix", "Hỗn hợp dưa leo, cà chua bi, hành tây tím", 280, "g"),
      ing("i2", "Lettuce", "Xà lách", 150, "g"),
      ing("i3", "Pineapple, diced", "Dứa cắt hạt lựu", 100, "g"),
      ing("i4", "Passion fruit pulp", "Thịt chanh dây", 100, "g"),
      ing("i5", "Sugar", "Đường", 43, "g"),
      ing("i6", "Oil", "Dầu ăn", 40, "ml"),
      ing("i7", "White vinegar", "Giấm trắng", 15, "ml"),
      ing("i8", "Salt", "Muối", 2, "g"),
      ing("i9", "Black pepper", "Tiêu đen", 1, "g"),
    ],
    steps: [
      step("s1", "Whisk passion fruit pulp, sugar, oil, vinegar, salt and pepper into a dressing.", "Đánh đều thịt chanh dây, đường, dầu, giấm, muối và tiêu thành nước sốt."),
      step("s2", "Toss cucumber mix, lettuce and pineapple with dressing to order.", "Trộn hỗn hợp dưa leo, xà lách và dứa với nước sốt khi lên món."),
    ],
    costPerPortionVnd: 2208,
    notes: { en: "Rebuilt recipe — feta removed. Sweet passion fruit dressing (not honey — swapped to sugar). No feta, no oregano.", vi: "Công thức đã chỉnh — bỏ feta. Sốt chanh dây ngọt (thay mật ong bằng đường). Không feta, không oregano." },
    updatedAt: NOW,
  },
  {
    id: "rc_escovitch_cold",
    name: { en: "Fresh Pickled Escovitch Sauce", vi: "Sốt Escovitch Ngâm Lạnh" },
    category: "side",
    basePortions: 10,
    ingredients: [
      ing("i1", "Carrot", "Cà rốt", 150, "g"),
      ing("i2", "Onion", "Hành tây", 280, "g"),
      ing("i3", "Red pepper", "Ớt chuông đỏ", 150, "g"),
      ing("i4", "Yellow pepper", "Ớt chuông vàng", 150, "g"),
      ing("i5", "Garlic", "Tỏi", 9, "g"),
      ing("i6", "Thyme", "Lá xạ hương (thyme)", 1, "g"),
      ing("i7", "Allspice", "Bột đa hương", 9, "g"),
      ing("i8", "White vinegar", "Giấm trắng", 480, "ml"),
      ing("i9", "Salt", "Muối", 5, "g"),
      ing("i10", "Sugar", "Đường", 25, "g"),
    ],
    steps: [
      step("s1", "Finely slice all vegetables.", "Thái mỏng tất cả rau củ."),
      step("s2", "Bring vinegar, salt and sugar to the boil to make the brine.", "Đun sôi giấm, muối và đường để làm nước ngâm."),
      step("s3", "Pour hot brine over raw vegetables. Cold pickle — vegetables are not cooked.", "Đổ nước ngâm nóng lên rau củ sống. Ngâm lạnh — không nấu rau củ."),
    ],
    updatedAt: NOW,
  },
  {
    id: "rc_escovitch_hot",
    name: { en: "Hot Pickled Escovitch Sauce", vi: "Sốt Escovitch Ngâm Cay" },
    category: "side",
    basePortions: 10,
    ingredients: [
      ing("i1", "Carrot", "Cà rốt", 150, "g"),
      ing("i2", "Onion", "Hành tây", 280, "g"),
      ing("i3", "Red pepper", "Ớt chuông đỏ", 150, "g"),
      ing("i4", "Yellow pepper", "Ớt chuông vàng", 150, "g"),
      ing("i5", "Garlic", "Tỏi", 9, "g"),
      ing("i6", "Thyme", "Lá xạ hương (thyme)", 1, "g"),
      ing("i7", "Allspice", "Bột đa hương", 9, "g"),
      ing("i8", "White vinegar", "Giấm trắng", 480, "ml"),
      ing("i9", "Salt", "Muối", 5, "g"),
      ing("i10", "Sugar", "Đường", 25, "g"),
      ing("i11", "Scotch Bonnet", "Ớt Scotch Bonnet", 18, "g"),
      ing("i12", "Oil", "Dầu ăn", 20, "ml"),
    ],
    steps: [
      step("s1", "Sauté vegetables and Scotch Bonnet in oil first.", "Xào sơ rau củ và ớt Scotch Bonnet với dầu trước."),
      step("s2", "Bring vinegar, salt and sugar to the boil to make the brine.", "Đun sôi giấm, muối và đường để làm nước ngâm."),
      step("s3", "Pour hot brine over the sautéed vegetables and pickle.", "Đổ nước ngâm nóng lên rau củ đã xào và ngâm."),
    ],
    notes: { en: "The 'hot' version, both in heat (Scotch Bonnet) and technique (sautéed first, not raw).", vi: "Phiên bản 'cay' — cả về độ cay (Scotch Bonnet) lẫn cách làm (xào trước, không để sống)." },
    updatedAt: NOW,
  },
  {
    id: "rc_apple_crumble",
    name: { en: "Apple Crumble", vi: "Bánh Táo Nướng Giòn" },
    category: "dessert",
    basePortions: 10,
    ingredients: [
      ing("i1", "Apple, Fuji", "Táo Fuji", 800, "g"),
      ing("i2", "Sugar", "Đường", 80, "g"),
      ing("i3", "Cinnamon (filling)", "Bột quế (nhân)", 5, "g"),
      ing("i4", "Cinnamon (topping)", "Bột quế (phủ mặt)", 3, "g"),
      ing("i5", "Plain flour (filling)", "Bột mì thường (nhân)", 15, "g"),
      ing("i6", "Plain flour (topping)", "Bột mì thường (phủ mặt)", 150, "g"),
      ing("i7", "Brown sugar", "Đường nâu", 100, "g"),
      ing("i8", "Butter", "Bơ", 100, "g"),
    ],
    steps: [
      step("s1", "Toss diced apple with sugar, cinnamon and flour for the filling.", "Trộn táo cắt hạt lựu với đường, quế và bột mì làm nhân."),
      step("s2", "Rub topping flour, brown sugar, butter and cinnamon into a crumble.", "Bóp bột phủ mặt, đường nâu, bơ và quế thành hỗn hợp vụn giòn."),
      step("s3", "Top filling with crumble and bake at 180°C for 30–35 minutes.", "Phủ hỗn hợp vụn giòn lên nhân và nướng ở 180°C trong 30–35 phút."),
    ],
    costPerPortionVnd: 8868,
    notes: { en: "Replaces Peach Cobbler (local canned peach quality issue). No lime. Doubles as both the standalone Dessert and the Roast Sunday dessert.", vi: "Thay thế Bánh Đào Nướng (do chất lượng đào đóng hộp nội địa). Không dùng chanh. Dùng chung cho cả món Tráng miệng thường và Roast Sunday." },
    updatedAt: NOW,
  },
  {
    id: "rc_custard",
    name: { en: "Custard", vi: "Sốt Custard" },
    category: "dessert",
    basePortions: 10,
    ingredients: [
      ing("i1", "Milk", "Sữa tươi", 960, "ml"),
      ing("i2", "Lion Custard Powder", "Bột Custard Lion", 60, "g"),
      ing("i3", "Sugar", "Đường", 43, "g"),
    ],
    steps: [
      step("s1", "Warm milk gently, do not boil.", "Đun ấm sữa nhẹ nhàng, không để sôi."),
      step("s2", "Whisk in custard powder and sugar until thickened.", "Vừa đánh vừa cho bột custard và đường vào đến khi sánh đặc."),
    ],
    costPerPortionVnd: 3013,
    notes: { en: "Made from Lion Custard Powder — not from scratch. No eggs, cream, vanilla, or cornstarch.", vi: "Làm từ bột Custard Lion — không làm từ nguyên liệu thô. Không trứng, kem, vani hay bột bắp." },
    updatedAt: NOW,
  },
  {
    id: "rc_roast_chicken",
    name: { en: "Roast Chicken (Brine, Spatchcock & Grill)", vi: "Gà Nướng (Ướp Muối, Bổ Cánh Bướm & Nướng)" },
    category: "roast_sunday",
    basePortions: 4,
    ingredients: [
      ing("i1", "Water (brine)", "Nước (ngâm muối)", 2, "L"),
      ing("i2", "Salt (brine)", "Muối (ngâm)", 120, "g"),
      ing("i3", "Garlic (brine)", "Tỏi (ngâm)", 30, "g"),
      ing("i4", "Rosemary (brine)", "Hương thảo (ngâm)", 10, "g"),
      ing("i5", "Thyme (brine)", "Lá xạ hương (ngâm)", 10, "g"),
      ing("i6", "Whole allspice (brine)", "Đa hương nguyên hạt (ngâm)", 15, "g"),
      ing("i7", "Whole chicken", "Gà nguyên con", 1, "whole"),
    ],
    steps: [
      step("s1", "Combine brine ingredients, submerge chicken, refrigerate minimum 3 days.", "Trộn hỗn hợp ngâm, ngâm ngập gà, để tủ lạnh tối thiểu 3 ngày."),
      step("s2", "Spatchcock the chicken (remove backbone, flatten).", "Bổ cánh bướm con gà (bỏ xương sống, ép dẹt)."),
      step("s3", "Grill whole until core temp ≥75°C, then carve into quarters.", "Nướng nguyên con đến khi nhiệt độ lõi ≥75°C, sau đó chặt thành 4 phần."),
    ],
    notes: { en: "Roast Sunday only. 1 whole chicken feeds 4 people.", vi: "Chỉ dùng cho Roast Sunday. 1 con gà phục vụ 4 người." },
    updatedAt: NOW,
  },
  {
    id: "rc_gravy",
    name: { en: "Gravy", vi: "Nước Sốt Gravy" },
    category: "roast_sunday",
    basePortions: 10,
    ingredients: [
      ing("i1", "Butter", "Bơ", 60, "g"),
      ing("i2", "Onion", "Hành tây", 50, "g"),
      ing("i3", "Garlic", "Tỏi", 10, "g"),
      ing("i4", "Flour", "Bột mì", 60, "g"),
      ing("i5", "Water", "Nước", 720, "ml"),
      ing("i6", "Chicken powder", "Bột gà", 30, "g"),
      ing("i7", "Thyme", "Lá xạ hương (thyme)", 3, "g"),
      ing("i8", "Black pepper", "Tiêu đen", 2, "g"),
    ],
    steps: [
      step("s1", "Sweat onion and garlic in butter.", "Phi hành tây và tỏi với bơ."),
      step("s2", "Stir in flour to make a roux.", "Cho bột mì vào khuấy làm hỗn hợp roux."),
      step("s3", "Whisk in water and chicken powder, simmer until thickened.", "Vừa đánh vừa cho nước và bột gà vào, hầm đến khi sánh đặc."),
      step("s4", "Season with thyme and black pepper.", "Nêm thyme và tiêu đen."),
    ],
    costPerPortionVnd: 2202,
    notes: { en: "Chicken powder-based, not pan drippings — the chicken is grilled, not oven-roasted. Roast Sunday only.", vi: "Làm từ bột gà, không phải nước tiết ra từ khay — vì gà được nướng, không quay lò. Chỉ dùng cho Roast Sunday." },
    updatedAt: NOW,
  },
  {
    id: "rc_stuffing",
    name: { en: "Stuffing", vi: "Nhân Bánh Mì Nướng" },
    category: "roast_sunday",
    basePortions: 10,
    ingredients: [
      ing("i1", "Bread, cubed and dried", "Bánh mì cắt hạt lựu và sấy khô", 450, "g"),
      ing("i2", "Butter", "Bơ", 115, "g"),
      ing("i3", "Onion", "Hành tây", 200, "g"),
      ing("i4", "Celery", "Cần tây", 150, "g"),
      ing("i5", "Thyme", "Lá xạ hương (thyme)", 5, "g"),
      ing("i6", "Chicken powder", "Bột gà", 15, "g"),
      ing("i7", "Water", "Nước", 350, "ml"),
      ing("i8", "Salt", "Muối", 6, "g"),
      ing("i9", "Black pepper", "Tiêu đen", 2, "g"),
    ],
    steps: [
      step("s1", "Sweat onion and celery in butter with thyme.", "Phi hành tây và cần tây với bơ cùng thyme."),
      step("s2", "Combine with bread cubes, chicken powder, water, salt and pepper.", "Trộn với bánh mì cắt hạt lựu, bột gà, nước, muối và tiêu."),
      step("s3", "Bake separately as a dressing-style side (not stuffed inside the bird).", "Nướng riêng theo kiểu món phụ (không nhồi vào trong con gà)."),
    ],
    notes: { en: "Roast Sunday only.", vi: "Chỉ dùng cho Roast Sunday." },
    updatedAt: NOW,
  },
  {
    id: "rc_rum_punch",
    name: { en: "Classic Rum Punch", vi: "Rum Punch Cổ Điển" },
    category: "cocktail",
    basePortions: 1,
    ingredients: [
      ing("i1", "White rum", "Rượu rum trắng", 45, "ml"),
      ing("i2", "Orange juice", "Nước cam", 30, "ml"),
      ing("i3", "Pineapple juice", "Nước dứa", 30, "ml"),
      ing("i4", "Grenadine", "Si rô lựu (grenadine)", 10, "ml"),
      ing("i5", "Lime juice", "Nước cốt chanh", 10, "ml"),
      ing("i6", "Grated nutmeg", "Hạt nhục đậu khấu bào", 1, "pinch"),
    ],
    steps: [
      step("s1", "Shake all ingredients with ice.", "Lắc đều tất cả nguyên liệu với đá."),
      step("s2", "Strain over fresh ice, garnish with grated nutmeg.", "Lọc ra ly đá mới, rắc nhục đậu khấu bào lên trên."),
    ],
    notes: { en: "Mocktail available — omit rum, top with soda.", vi: "Có phiên bản mocktail — bỏ rum, thêm soda." },
    updatedAt: NOW,
  },
  {
    id: "rc_sorrel_daiquiri",
    name: { en: "Sunset Sorrel Daiquiri", vi: "Sunset Sorrel Daiquiri" },
    category: "cocktail",
    basePortions: 1,
    ingredients: [
      ing("i1", "White rum", "Rượu rum trắng", 45, "ml"),
      ing("i2", "Sorrel (hibiscus) syrup", "Si rô sorrel (atiso đỏ)", 20, "ml"),
      ing("i3", "Lime juice", "Nước cốt chanh", 20, "ml"),
      ing("i4", "Sugar syrup", "Si rô đường", 10, "ml"),
    ],
    steps: [
      step("s1", "Shake all ingredients with ice.", "Lắc đều tất cả nguyên liệu với đá."),
      step("s2", "Double strain into a chilled coupe.", "Lọc kỹ ra ly coupe đã làm lạnh."),
    ],
    notes: { en: "Mocktail available.", vi: "Có phiên bản mocktail." },
    updatedAt: NOW,
  },
  {
    id: "rc_blue_mountain_mule",
    name: { en: "Blue Mountain Mule", vi: "Blue Mountain Mule" },
    category: "cocktail",
    basePortions: 1,
    ingredients: [
      ing("i1", "Dark rum", "Rượu rum đen", 45, "ml"),
      ing("i2", "Ginger beer", "Bia gừng", 90, "ml"),
      ing("i3", "Lime juice", "Nước cốt chanh", 15, "ml"),
    ],
    steps: [
      step("s1", "Build over ice in a copper mug.", "Pha trực tiếp với đá trong ly đồng."),
      step("s2", "Top with ginger beer, garnish with lime wheel and mint.", "Thêm bia gừng, trang trí với lát chanh và bạc hà."),
    ],
    notes: { en: "Mocktail available.", vi: "Có phiên bản mocktail." },
    updatedAt: NOW,
  },
  {
    id: "rc_jerk_old_fashioned",
    name: { en: "Spiced Jerk Old Fashioned", vi: "Spiced Jerk Old Fashioned" },
    category: "cocktail",
    basePortions: 1,
    ingredients: [
      ing("i1", "Spiced rum", "Rượu rum gia vị", 60, "ml"),
      ing("i2", "Allspice dram", "Rượu đa hương (allspice dram)", 5, "ml"),
      ing("i3", "Angostura bitters", "Angostura bitters", 2, "dash"),
      ing("i4", "Sugar cube", "Đường viên", 1, "pc"),
    ],
    steps: [
      step("s1", "Muddle sugar cube with bitters.", "Nghiền đường viên với bitters."),
      step("s2", "Add rum and allspice dram, stir over ice.", "Thêm rum và allspice dram, khuấy với đá."),
      step("s3", "Strain over a large ice cube, garnish with orange peel.", "Lọc ra ly có đá viên lớn, trang trí với vỏ cam."),
    ],
    notes: { en: "Mocktail available.", vi: "Có phiên bản mocktail." },
    updatedAt: NOW,
  },
  {
    id: "rc_ting_rum_fizz",
    name: { en: "Ting & Rum Fizz", vi: "Ting & Rum Fizz" },
    category: "cocktail",
    basePortions: 1,
    ingredients: [
      ing("i1", "White rum", "Rượu rum trắng", 45, "ml"),
      ing("i2", "Ting (grapefruit soda)", "Ting (soda bưởi)", 90, "ml"),
      ing("i3", "Lime juice", "Nước cốt chanh", 10, "ml"),
    ],
    steps: [
      step("s1", "Build over ice.", "Pha trực tiếp với đá."),
      step("s2", "Top with Ting, garnish with grapefruit twist.", "Thêm Ting, trang trí với vỏ bưởi xoắn."),
    ],
    notes: { en: "Mocktail available.", vi: "Có phiên bản mocktail." },
    updatedAt: NOW,
  },
];
