import type { Recipe } from "@/lib/types";

const NOW = "2026-08-19T00:00:00.000Z";

function ing(id: string, en: string, vi: string, qty: number, unit: string) {
  return { id, name: { en, vi }, qty, unit };
}

function step(id: string, en: string, vi: string) {
  return { id, text: { en, vi } };
}

export const SEED_RECIPES: Recipe[] = [
  {
    id: "rc_jerk_chicken",
    name: { en: "Jerk Chicken Meal", vi: "Gà Jerk" },
    category: "main",
    basePortions: 12,
    ingredients: [
      ing("i1", "Chicken leg quarters", "Đùi gà nguyên", 12, "pcs"),
      ing("i2", "Jerk marinade", "Sốt ướp Jerk", 1, "batch (confidential — ask Head Chef)"),
      ing("i3", "Rice and Peas", "Cơm đậu", 12, "portion"),
      ing("i4", "Steamed Veg", "Rau củ hấp", 12, "portion"),
      ing("i5", "Plantain", "Chuối chiên", 12, "portion"),
    ],
    steps: [
      step("s1", "Marinate chicken in Jerk marinade — minimum 24h.", "Ướp gà với sốt Jerk — tối thiểu 24 giờ."),
      step("s2", "Bring chicken to room temp 20 min before grilling.", "Để gà ở nhiệt độ phòng 20 phút trước khi nướng."),
      step("s3", "Grill over charcoal, turning regularly, until core temp ≥75°C.", "Nướng trên than hoa, lật đều tay, đến khi nhiệt độ lõi ≥75°C."),
      step("s4", "Rest 5 minutes, then plate with Rice and Peas, Steamed Veg and Plantain.", "Để nghỉ 5 phút, sau đó bày cùng Cơm đậu, Rau củ hấp và Chuối chiên."),
    ],
    notes: {
      en: "Jerk marinade recipe is confidential and intentionally not listed here — Head Chef only, per standing kitchen rule.",
      vi: "Công thức sốt ướp Jerk là bí mật và cố tình không liệt kê ở đây — chỉ Bếp trưởng biết, theo quy định bếp.",
    },
    updatedAt: NOW,
  },
  {
    id: "rc_rice_peas",
    name: { en: "Rice and Peas", vi: "Cơm Đậu" },
    category: "side",
    basePortions: 36,
    ingredients: [
      // Pack sizes are written per-can, not as a total can count — a count
      // would go stale the moment the recipe is scaled, since only the number
      // scales and the unit text doesn't.
      ing("i1", "Kidney beans, canned (whole cans, not drained)", "Đậu đỏ đóng hộp (nguyên hộp, không để ráo)", 1600, "g (400g cans)"),
      ing("i2", "Coconut milk", "Nước cốt dừa", 880, "ml (440ml cans)"),
      ing("i3", "Water", "Nước", 800, "ml"),
      ing("i4", "Long grain rice", "Gạo tẻ hạt dài", 2000, "g"),
      ing("i5", "Sea salt", "Muối biển", 36, "g"),
      ing("i6", "Scallion", "Hành lá", 120, "g"),
      ing("i7", "Garlic", "Tỏi", 24, "g"),
      ing("i8", "Pimento / allspice", "Bột đa hương (pimento)", 16, "g"),
      ing("i9", "Thyme", "Lá xạ hương (thyme)", 12, "g"),
    ],
    steps: [
      step("s1", "Combine everything in a pot.", "Cho tất cả nguyên liệu vào nồi."),
      step("s2", "Bring to the boil, then simmer 15 min on medium heat.", "Đun sôi, sau đó hầm 15 phút ở lửa vừa."),
      step("s3", "Simmer a further 5–10 min on low heat.", "Hầm thêm 5–10 phút ở lửa nhỏ."),
      step("s4", "Rest 10 minutes, covered, before serving.", "Để nghỉ 10 phút, đậy nắp, trước khi phục vụ."),
    ],
    costPerPortionVnd: 7358,
    notes: { en: "150g portion. This is a real batch — scales from 36 portions, not 12.", vi: "Khẩu phần 150g. Đây là mẻ thật — nhân từ 36 khẩu phần, không phải 12." },
    updatedAt: NOW,
  },
  {
    id: "rc_steamed_veg",
    name: { en: "Steamed Veg", vi: "Rau Củ Hấp" },
    category: "side",
    basePortions: 12,
    ingredients: [
      ing("i1", "Oil", "Dầu ăn", 30, "ml"),
      ing("i2", "Onion", "Hành tây", 70, "g"),
      ing("i3", "Garlic", "Tỏi", 15, "g"),
      ing("i4", "Thyme, sprigs tied", "Lá xạ hương (bó cọng)", 6, "g"),
      ing("i5", "White cabbage", "Bắp cải trắng", 250, "g"),
      ing("i6", "Carrot, julienned", "Cà rốt (thái sợi)", 250, "g"),
      ing("i7", "Red pepper", "Ớt chuông đỏ", 300, "g"),
      ing("i8", "Water", "Nước", 60, "ml"),
      ing("i9", "All-purpose seasoning", "Gia vị tổng hợp", 5, "g"),
      ing("i10", "Black pepper", "Tiêu đen", 3, "g"),
      ing("i11", "Salt", "Muối", 9, "g"),
    ],
    steps: [
      step("s1", "Heat oil, sauté onion, garlic and tied thyme sprigs until soft.", "Đun nóng dầu, phi hành tây, tỏi và bó thyme đến khi mềm."),
      step("s2", "Add cabbage, carrot and red pepper, stir 5 minutes.", "Cho bắp cải, cà rốt và ớt chuông đỏ vào, đảo 5 phút."),
      step("s3", "Lower heat, add water, cover and steam 10 minutes.", "Hạ lửa, thêm nước, đậy nắp và hấp 10 phút."),
      step("s4", "Remove lid, season with all-purpose seasoning, black pepper and salt.", "Mở nắp, nêm gia vị tổng hợp, tiêu đen và muối."),
      step("s5", "Remove thyme sprigs before serving.", "Bỏ bó thyme trước khi phục vụ."),
    ],
    updatedAt: NOW,
  },
  {
    id: "rc_plantain",
    name: { en: "Plantain", vi: "Chuối Chiên" },
    category: "side",
    basePortions: 12,
    ingredients: [ing("i1", "Plantain (chuối già, Kamereo A375)", "Chuối già (Kamereo A375)", 6, "whole (~180g each)")],
    steps: [
      step("s1", "Peel plantains.", "Gọt vỏ chuối."),
      step("s2", "Cut into 8 pieces each.", "Cắt mỗi quả thành 8 miếng."),
      step("s3", "Shallow fry until golden.", "Chiên ngập một nửa đến khi vàng."),
    ],
    costPerPortionVnd: 1890,
    notes: { en: "1 portion = 4 pieces. Bundled into the Jerk Chicken Meal, not a standalone side.", vi: "1 khẩu phần = 4 miếng. Đi kèm trong Gà Jerk, không bán riêng." },
    updatedAt: NOW,
  },
  {
    id: "rc_fried_dumplings",
    name: { en: "Fried Dumplings", vi: "Bánh Bột Chiên" },
    category: "side",
    basePortions: 12,
    ingredients: [
      ing("i1", "All-purpose flour", "Bột mì đa dụng", 290, "g"),
      ing("i2", "Baking powder", "Bột nở", 17, "g"),
      ing("i3", "Sea salt", "Muối biển", 5.9, "g"),
      ing("i4", "Granulated sugar", "Đường trắng", 24, "g"),
      ing("i5", "Vegan butter", "Bơ thực vật", 69, "g"),
      ing("i6", "Warm water", "Nước ấm", 194, "g"),
    ],
    steps: [
      step("s1", "Mix dry ingredients, rub in butter, bring together with warm water.", "Trộn nguyên liệu khô, bóp bơ vào, nhồi cùng nước ấm."),
      step("s2", "Divide into 12 pieces (50g each).", "Chia thành 12 phần (mỗi phần 50g)."),
      step("s3", "Check fryer ready-light (green on, red off) before frying.", "Kiểm tra đèn báo chảo chiên (xanh sáng, đỏ tắt) trước khi chiên."),
      step("s4", "Fry at 170°C, ~6–8 minutes.", "Chiên ở 170°C, khoảng 6–8 phút."),
    ],
    costPerPortionVnd: 2501,
    notes: { en: "Cost is per piece (12 pieces, 50g each).", vi: "Giá tính theo miếng (12 miếng, mỗi miếng 50g)." },
    updatedAt: NOW,
  },
  {
    id: "rc_mac_cheese",
    name: { en: "Mac and Cheese", vi: "Mì Ống Phô Mai" },
    category: "side",
    basePortions: 12,
    ingredients: [
      ing("i1", "Milk", "Sữa tươi", 355, "ml"),
      ing("i2", "Cream", "Kem tươi", 240, "ml"),
      ing("i3", "Macaroni", "Nui ống (macaroni)", 454, "g"),
      ing("i4", "Cheddar", "Phô mai Cheddar", 440, "g"),
      ing("i5", "Parmesan", "Phô mai Parmesan", 100, "g"),
      ing("i6", "Butter", "Bơ", 100, "g"),
      ing("i7", "Salt", "Muối", 6, "g"),
      ing("i8", "Black pepper", "Tiêu đen", 2.4, "g"),
    ],
    steps: [
      step("s1", "Cook macaroni until just al dente.", "Luộc nui đến khi vừa chín tới."),
      step("s2", "Warm milk and cream, melt in butter, cheddar and parmesan.", "Đun ấm sữa và kem, cho bơ, cheddar và parmesan vào tan chảy."),
      step("s3", "Combine with macaroni, season with salt and black pepper.", "Trộn với nui, nêm muối và tiêu đen."),
    ],
    costPerPortionVnd: 27601,
    notes: { en: "~55% food cost — accepted as-is, cheese is genuinely expensive with no fix available without changing the dish.", vi: "Chi phí nguyên liệu ~55% — chấp nhận vì phô mai vốn đắt, không có cách giảm nếu không đổi công thức." },
    updatedAt: NOW,
  },
  {
    id: "rc_house_salad",
    name: { en: "House Salad", vi: "Salad Nhà Làm" },
    category: "side",
    basePortions: 12,
    ingredients: [
      ing("i1", "Cucumber, cherry tomato, red onion mix", "Hỗn hợp dưa leo, cà chua bi, hành tây tím", 280, "g"),
      ing("i2", "Lettuce", "Xà lách", 150, "g"),
      ing("i3", "Pineapple, diced", "Dứa cắt hạt lựu", 100, "g"),
      ing("i4", "Passion fruit pulp", "Thịt chanh dây", 100, "g"),
      ing("i5", "Sugar", "Đường", 60, "g"),
      ing("i6", "Oil", "Dầu ăn", 40, "ml"),
      ing("i7", "White vinegar", "Giấm trắng", 15, "ml"),
      ing("i8", "Salt", "Muối", 2, "g"),
      ing("i9", "Black pepper", "Tiêu đen", 1, "g"),
    ],
    steps: [
      step("s1", "Whisk passion fruit pulp, sugar, oil, vinegar, salt and pepper into a dressing.", "Đánh đều thịt chanh dây, đường, dầu, giấm, muối và tiêu thành nước sốt."),
      step("s2", "Toss cucumber mix, lettuce and pineapple with dressing to order.", "Trộn hỗn hợp dưa leo, xà lách và dứa với nước sốt khi lên món."),
    ],
    costPerPortionVnd: 2208,
    notes: { en: "Rebuilt recipe — feta removed. Sweet passion fruit dressing (honey swapped for sugar, same weight). No feta, no oregano.", vi: "Công thức đã chỉnh — bỏ feta. Sốt chanh dây ngọt (thay mật ong bằng đường, cùng khối lượng). Không feta, không oregano." },
    updatedAt: NOW,
  },
  {
    id: "rc_escovitch_cold",
    name: { en: "Fresh Pickled Escovitch Sauce", vi: "Sốt Escovitch Ngâm Lạnh" },
    category: "side",
    basePortions: 12,
    ingredients: [
      ing("i1", "Carrot", "Cà rốt", 150, "g"),
      ing("i2", "Onion", "Hành tây", 280, "g"),
      ing("i3", "Red pepper", "Ớt chuông đỏ", 150, "g"),
      ing("i4", "Yellow pepper", "Ớt chuông vàng", 150, "g"),
      ing("i5", "Garlic", "Tỏi", 9, "g"),
      ing("i6", "Thyme", "Lá xạ hương (thyme)", 1, "g"),
      ing("i7", "Allspice", "Bột đa hương", 9, "g"),
      ing("i8", "White vinegar", "Giấm trắng", 480, "ml"),
      ing("i9", "Salt", "Muối", 5, "g"),
      ing("i10", "Sugar", "Đường", 25, "g"),
    ],
    steps: [
      step("s1", "Finely slice all vegetables.", "Thái mỏng tất cả rau củ."),
      step("s2", "Bring vinegar, salt and sugar to the boil to make the brine.", "Đun sôi giấm, muối và đường để làm nước ngâm."),
      step("s3", "Pour hot brine over raw vegetables. Cold pickle — vegetables are not cooked.", "Đổ nước ngâm nóng lên rau củ sống. Ngâm lạnh — không nấu rau củ."),
    ],
    updatedAt: NOW,
  },
  {
    id: "rc_escovitch_hot",
    name: { en: "Hot Pickled Escovitch Sauce", vi: "Sốt Escovitch Ngâm Cay" },
    category: "side",
    basePortions: 12,
    ingredients: [
      ing("i1", "Carrot", "Cà rốt", 150, "g"),
      ing("i2", "Onion", "Hành tây", 280, "g"),
      ing("i3", "Red pepper", "Ớt chuông đỏ", 150, "g"),
      ing("i4", "Yellow pepper", "Ớt chuông vàng", 150, "g"),
      ing("i5", "Garlic", "Tỏi", 8, "g"),
      ing("i6", "Thyme", "Lá xạ hương (thyme)", 1, "g"),
      ing("i7", "Allspice", "Bột đa hương", 9, "g"),
      ing("i8", "White vinegar", "Giấm trắng", 480, "ml"),
      ing("i9", "Salt", "Muối", 5, "g"),
      ing("i10", "Sugar", "Đường", 25, "g"),
      ing("i11", "Scotch Bonnet", "Ớt Scotch Bonnet", 18, "g"),
      ing("i12", "Oil", "Dầu ăn", 20, "ml"),
    ],
    steps: [
      step("s1", "Sauté vegetables and Scotch Bonnet in oil first.", "Xào sơ rau củ và ớt Scotch Bonnet với dầu trước."),
      step("s2", "Bring vinegar, salt and sugar to the boil to make the brine.", "Đun sôi giấm, muối và đường để làm nước ngâm."),
      step("s3", "Pour hot brine over the sautéed vegetables and pickle.", "Đổ nước ngâm nóng lên rau củ đã xào và ngâm."),
    ],
    notes: { en: "The 'hot' version, both in heat (Scotch Bonnet) and technique (sautéed first, not raw).", vi: "Phiên bản 'cay' — cả về độ cay (Scotch Bonnet) lẫn cách làm (xào trước, không để sống)." },
    updatedAt: NOW,
  },
  {
    id: "rc_apple_crumble",
    name: { en: "Apple Crumble", vi: "Bánh Táo Nướng Giòn" },
    category: "dessert",
    basePortions: 12,
    ingredients: [
      ing("i1", "Apple, Fuji", "Táo Fuji", 800, "g"),
      ing("i2", "Sugar", "Đường", 80, "g"),
      ing("i3", "Cinnamon (filling)", "Bột quế (nhân)", 5, "g"),
      ing("i4", "Cinnamon (topping)", "Bột quế (phủ mặt)", 3, "g"),
      ing("i5", "Plain flour (filling)", "Bột mì thường (nhân)", 15, "g"),
      ing("i6", "Plain flour (topping)", "Bột mì thường (phủ mặt)", 150, "g"),
      ing("i7", "Brown sugar", "Đường nâu", 100, "g"),
      ing("i8", "Butter", "Bơ", 100, "g"),
    ],
    steps: [
      step("s1", "Toss diced apple with sugar, cinnamon and flour for the filling.", "Trộn táo cắt hạt lựu với đường, quế và bột mì làm nhân."),
      step("s2", "Rub topping flour, brown sugar, butter and cinnamon into a crumble.", "Bóp bột phủ mặt, đường nâu, bơ và quế thành hỗn hợp vụn giòn."),
      step("s3", "Top filling with crumble and bake at 180°C for 30–35 minutes.", "Phủ hỗn hợp vụn giòn lên nhân và nướng ở 180°C trong 30–35 phút."),
    ],
    costPerPortionVnd: 8868,
    notes: { en: "Replaces Peach Cobbler (local canned peach quality issue). No lime. Doubles as both the standalone Dessert and the Roast Sunday dessert.", vi: "Thay thế Bánh Đào Nướng (do chất lượng đào đóng hộp nội địa). Không dùng chanh. Dùng chung cho cả món Tráng miệng thường và Roast Sunday." },
    updatedAt: NOW,
  },
  {
    id: "rc_custard",
    name: { en: "Custard", vi: "Sốt Custard" },
    category: "dessert",
    basePortions: 12,
    ingredients: [
      ing("i1", "Milk", "Sữa tươi", 960, "ml"),
      ing("i2", "Lion Custard Powder", "Bột Custard Lion", 60, "g"),
      ing("i3", "Sugar", "Đường", 43, "g"),
    ],
    steps: [
      step("s1", "Warm milk gently, do not boil.", "Đun ấm sữa nhẹ nhàng, không để sôi."),
      step("s2", "Whisk in custard powder and sugar until thickened.", "Vừa đánh vừa cho bột custard và đường vào đến khi sánh đặc."),
    ],
    costPerPortionVnd: 3013,
    notes: { en: "Made from Lion Custard Powder — not from scratch. No eggs, cream, vanilla, or cornstarch.", vi: "Làm từ bột Custard Lion — không làm từ nguyên liệu thô. Không trứng, kem, vani hay bột bắp." },
    updatedAt: NOW,
  },
  {
    id: "rc_roast_chicken",
    name: { en: "Roast Chicken (Brine, Spatchcock & Grill)", vi: "Gà Nướng (Ướp Muối, Bổ Cánh Bướm & Nướng)" },
    category: "roast_sunday",
    basePortions: 12,
    ingredients: [
      ing("i1", "Water (brine)", "Nước (ngâm muối)", 2, "L"),
      ing("i2", "Salt (brine)", "Muối (ngâm)", 120, "g"),
      ing("i3", "Garlic (brine)", "Tỏi (ngâm)", 30, "g"),
      ing("i4", "Rosemary (brine)", "Hương thảo (ngâm)", 10, "g"),
      ing("i5", "Thyme (brine)", "Lá xạ hương (ngâm)", 10, "g"),
      ing("i6", "Whole allspice (brine)", "Đa hương nguyên hạt (ngâm)", 15, "g"),
      ing("i7", "Whole chicken", "Gà nguyên con", 3, "whole"),
    ],
    steps: [
      step("s1", "Combine brine ingredients, submerge chicken, refrigerate minimum 3 days.", "Trộn hỗn hợp ngâm, ngâm ngập gà, để tủ lạnh tối thiểu 3 ngày."),
      step("s2", "Spatchcock the chicken (remove backbone, flatten).", "Bổ cánh bướm con gà (bỏ xương sống, ép dẹt)."),
      step("s3", "Grill whole until core temp ≥75°C, then carve into quarters.", "Nướng nguyên con đến khi nhiệt độ lõi ≥75°C, sau đó chặt thành 4 phần."),
    ],
    notes: { en: "Roast Sunday only. 1 whole chicken feeds 4 people (3 chickens per 12-portion brine batch).", vi: "Chỉ dùng cho Roast Sunday. 1 con gà phục vụ 4 người (3 con gà cho mẻ ngâm 12 khẩu phần)." },
    updatedAt: NOW,
  },
  {
    id: "rc_roast_potato",
    name: { en: "Roast Potato", vi: "Khoai Tây Nướng" },
    category: "roast_sunday",
    basePortions: 12,
    ingredients: [
      ing("i1", "Potato", "Khoai tây", 1800, "g"),
      ing("i2", "Salt", "Muối", 18, "g"),
      ing("i3", "Rosemary", "Hương thảo", 7.2, "g"),
      ing("i4", "Black pepper", "Tiêu đen", 5.4, "g"),
    ],
    steps: [
      step("s1", "Peel and cut potato into even chunks, parboil until just tender.", "Gọt vỏ và cắt khoai tây thành miếng đều, luộc sơ đến khi vừa mềm."),
      step("s2", "Roughen the edges by shaking in the colander, toss with oil, salt, rosemary and pepper.", "Lắc rổ để khoai xù cạnh, trộn với dầu, muối, hương thảo và tiêu."),
      step("s3", "Roast at high heat, turning occasionally, until golden and crisp.", "Nướng ở nhiệt cao, thỉnh thoảng lật, đến khi vàng giòn."),
    ],
    costPerPortionVnd: 4344,
    notes: { en: "Roast Sunday only. Salt/rosemary/pepper quantities are estimates pending final chef confirmation.", vi: "Chỉ dùng cho Roast Sunday. Lượng muối/hương thảo/tiêu là ước tính, chờ bếp trưởng xác nhận cuối cùng." },
    updatedAt: NOW,
  },
  {
    id: "rc_long_stem_broccoli",
    name: { en: "Long Stem Broccoli", vi: "Bông Cải Xanh Cọng Dài" },
    category: "roast_sunday",
    basePortions: 12,
    ingredients: [ing("i1", "Long stem broccoli", "Bông cải xanh cọng dài", 960, "g")],
    steps: [
      step("s1", "Trim stems, blanch in salted boiling water until just tender.", "Cắt gọn cọng, chần trong nước sôi có muối đến khi vừa mềm."),
      step("s2", "Shock in iced water to hold colour, drain well.", "Ngâm ngay vào nước đá để giữ màu, để ráo."),
      step("s3", "Reheat to order — sauté or steam, season and serve.", "Hâm nóng lại khi lên món — xào hoặc hấp, nêm gia vị và phục vụ."),
    ],
    costPerPortionVnd: 5124,
    notes: { en: "Roast Sunday only.", vi: "Chỉ dùng cho Roast Sunday." },
    updatedAt: NOW,
  },
  {
    id: "rc_baby_carrot",
    name: { en: "Baby Carrot in Orange Sauce", vi: "Cà Rốt Baby Sốt Cam" },
    category: "roast_sunday",
    basePortions: 12,
    ingredients: [
      ing("i1", "Baby carrot", "Cà rốt baby", 1000, "g"),
      ing("i2", "Butter", "Bơ", 75, "g"),
      ing("i3", "Orange juice", "Nước cam", 100, "ml"),
      ing("i4", "Honey", "Mật ong", 110, "g"),
      ing("i5", "Salt", "Muối", 3, "g"),
      ing("i6", "Black pepper", "Tiêu đen", 1, "g"),
    ],
    steps: [
      step("s1", "Blanch baby carrots until just tender.", "Chần cà rốt baby đến khi vừa mềm."),
      step("s2", "Melt butter, add orange juice and honey, simmer to a glaze.", "Đun chảy bơ, thêm nước cam và mật ong, hầm thành nước sốt sánh."),
      step("s3", "Toss carrots in the glaze, season with salt and pepper.", "Trộn cà rốt với nước sốt, nêm muối và tiêu."),
    ],
    costPerPortionVnd: 14456,
    notes: { en: "Roast Sunday only.", vi: "Chỉ dùng cho Roast Sunday." },
    updatedAt: NOW,
  },
  {
    id: "rc_butternut_squash",
    name: { en: "Butternut Squash", vi: "Bí Đỏ Butternut" },
    category: "roast_sunday",
    basePortions: 12,
    ingredients: [
      ing("i1", "Butternut squash", "Bí đỏ butternut", 1200, "g"),
      ing("i2", "Olive oil", "Dầu ô liu", 50, "ml"),
      ing("i3", "Salt", "Muối", 6, "g"),
      ing("i4", "Black pepper", "Tiêu đen", 2, "g"),
      ing("i5", "Thyme", "Lá xạ hương (thyme)", 3, "g"),
    ],
    steps: [
      step("s1", "Peel and cut squash into even wedges.", "Gọt vỏ và cắt bí thành múi đều."),
      step("s2", "Toss with olive oil, salt, pepper and thyme.", "Trộn với dầu ô liu, muối, tiêu và thyme."),
      step("s3", "Roast until tender and caramelised at the edges.", "Nướng đến khi mềm và cạnh hơi cháy caramel."),
    ],
    costPerPortionVnd: 2653,
    notes: { en: "Roast Sunday only.", vi: "Chỉ dùng cho Roast Sunday." },
    updatedAt: NOW,
  },
  {
    id: "rc_yorkshire_pudding",
    name: { en: "Yorkshire Pudding", vi: "Bánh Yorkshire" },
    category: "roast_sunday",
    basePortions: 12,
    ingredients: [
      ing("i1", "Egg", "Trứng", 4, "pcs"),
      ing("i2", "Plain flour", "Bột mì thường", 150, "g"),
      ing("i3", "Milk", "Sữa tươi", 200, "ml"),
      ing("i4", "Oil", "Dầu ăn", 60, "ml"),
    ],
    steps: [
      step("s1", "Whisk egg, flour and milk into a smooth batter, rest 30 min.", "Đánh trứng, bột mì và sữa thành hỗn hợp mịn, để nghỉ 30 phút."),
      step("s2", "Heat oil in the tin until smoking hot.", "Đun nóng dầu trong khuôn đến khi bốc khói."),
      step("s3", "Pour batter into hot oil, bake at high heat until well risen and golden — do not open the oven early.", "Đổ hỗn hợp vào dầu nóng, nướng ở nhiệt cao đến khi nở phồng và vàng đều — không mở lò sớm."),
    ],
    costPerPortionVnd: 2181,
    notes: { en: "Roast Sunday only.", vi: "Chỉ dùng cho Roast Sunday." },
    updatedAt: NOW,
  },
  {
    id: "rc_gravy",
    name: { en: "Gravy", vi: "Nước Sốt Gravy" },
    category: "roast_sunday",
    basePortions: 12,
    ingredients: [
      ing("i1", "Butter", "Bơ", 60, "g"),
      ing("i2", "Onion", "Hành tây", 50, "g"),
      ing("i3", "Garlic", "Tỏi", 10, "g"),
      ing("i4", "Flour", "Bột mì", 60, "g"),
      ing("i5", "Water", "Nước", 720, "ml"),
      ing("i6", "Chicken powder", "Bột gà", 30, "g"),
      ing("i7", "Thyme", "Lá xạ hương (thyme)", 3, "g"),
      ing("i8", "Black pepper", "Tiêu đen", 2, "g"),
    ],
    steps: [
      step("s1", "Sweat onion and garlic in butter.", "Phi hành tây và tỏi với bơ."),
      step("s2", "Stir in flour to make a roux.", "Cho bột mì vào khuấy làm hỗn hợp roux."),
      step("s3", "Whisk in water and chicken powder, simmer until thickened.", "Vừa đánh vừa cho nước và bột gà vào, hầm đến khi sánh đặc."),
      step("s4", "Season with thyme and black pepper.", "Nêm thyme và tiêu đen."),
    ],
    costPerPortionVnd: 2202,
    notes: { en: "Chicken powder-based, not pan drippings — the chicken is grilled, not oven-roasted. Roast Sunday only.", vi: "Làm từ bột gà, không phải nước tiết ra từ khay — vì gà được nướng, không quay lò. Chỉ dùng cho Roast Sunday." },
    updatedAt: NOW,
  },
  {
    id: "rc_stuffing",
    name: { en: "Stuffing", vi: "Nhân Bánh Mì Nướng" },
    category: "roast_sunday",
    basePortions: 12,
    ingredients: [
      ing("i1", "Bread, cubed and dried", "Bánh mì cắt hạt lựu và sấy khô", 450, "g"),
      ing("i2", "Butter", "Bơ", 115, "g"),
      ing("i3", "Onion", "Hành tây", 200, "g"),
      ing("i4", "Celery", "Cần tây", 150, "g"),
      ing("i5", "Thyme", "Lá xạ hương (thyme)", 5, "g"),
      ing("i6", "Chicken powder", "Bột gà", 15, "g"),
      ing("i7", "Water", "Nước", 350, "ml"),
      ing("i8", "Salt", "Muối", 6, "g"),
      ing("i9", "Black pepper", "Tiêu đen", 2, "g"),
    ],
    steps: [
      step("s1", "Sweat onion and celery in butter with thyme.", "Phi hành tây và cần tây với bơ cùng thyme."),
      step("s2", "Combine with bread cubes, chicken powder, water, salt and pepper.", "Trộn với bánh mì cắt hạt lựu, bột gà, nước, muối và tiêu."),
      step("s3", "Bake separately as a dressing-style side (not stuffed inside the bird).", "Nướng riêng theo kiểu món phụ (không nhồi vào trong con gà)."),
    ],
    notes: { en: "Roast Sunday only.", vi: "Chỉ dùng cho Roast Sunday." },
    updatedAt: NOW,
  },
  {
    id: "rc_pickled_veg",
    name: { en: "Pickled Veg", vi: "Rau Củ Ngâm Chua" },
    category: "side",
    basePortions: 1,
    ingredients: [
      ing("i1", "Carrot", "Cà rốt", 400, "g"),
      ing("i2", "Cucumber", "Dưa leo", 400, "g"),
      ing("i3", "Cauliflower", "Súp lơ trắng", 300, "g"),
      ing("i4", "White vinegar", "Giấm trắng", 500, "ml"),
      ing("i5", "Water", "Nước", 300, "ml"),
      ing("i6", "Sugar", "Đường", 100, "g"),
      ing("i7", "Salt", "Muối", 40, "g"),
      ing("i8", "Garlic", "Tỏi", 20, "g"),
      ing("i9", "Bay leaf", "Lá nguyệt quế", 2, "g"),
    ],
    steps: [
      step("s1", "Cut vegetables into even pieces.", "Cắt rau củ thành miếng đều."),
      step("s2", "Bring vinegar, water, sugar, salt, garlic and bay leaf to the boil for the brine.", "Đun sôi giấm, nước, đường, muối, tỏi và lá nguyệt quế làm nước ngâm."),
      step("s3", "Pour hot brine over vegetables, cool, then refrigerate at least 24h before use.", "Đổ nước ngâm nóng lên rau củ, để nguội, sau đó để tủ lạnh ít nhất 24 giờ trước khi dùng."),
    ],
    notes: { en: "Fixed batch — makes ~1.5kg. Not portion-scaled like the main recipes.", vi: "Mẻ cố định — cho ra ~1.5kg. Không nhân theo khẩu phần như các công thức chính." },
    updatedAt: NOW,
  },
  {
    id: "rc_spicy_pickles",
    name: { en: "Spicy Pickles", vi: "Dưa Chua Cay" },
    category: "side",
    basePortions: 1,
    ingredients: [
      ing("i1", "Scotch Bonnet", "Ớt Scotch Bonnet", 150, "g"),
      ing("i2", "Carrot", "Cà rốt", 200, "g"),
      ing("i3", "Cucumber", "Dưa leo", 200, "g"),
      ing("i4", "Garlic", "Tỏi", 30, "g"),
      ing("i5", "White vinegar", "Giấm trắng", 400, "ml"),
      ing("i6", "Sugar", "Đường", 60, "g"),
      ing("i7", "Salt", "Muối", 20, "g"),
    ],
    steps: [
      step("s1", "Slice Scotch Bonnet, carrot and cucumber.", "Thái ớt Scotch Bonnet, cà rốt và dưa leo."),
      step("s2", "Bring vinegar, sugar and salt to the boil for the brine.", "Đun sôi giấm, đường và muối làm nước ngâm."),
      step("s3", "Pour hot brine over vegetables and garlic, cool, then refrigerate at least 24h before use.", "Đổ nước ngâm nóng lên rau củ và tỏi, để nguội, sau đó để tủ lạnh ít nhất 24 giờ trước khi dùng."),
    ],
    notes: { en: "Fixed batch — makes ~1kg. Handle Scotch Bonnet with gloves. Not portion-scaled like the main recipes.", vi: "Mẻ cố định — cho ra ~1kg. Đeo găng tay khi xử lý ớt Scotch Bonnet. Không nhân theo khẩu phần như các công thức chính." },
    updatedAt: NOW,
  },
  {
    id: "rc_sugar_syrup",
    name: { en: "Sugar Syrup", vi: "Si Rô Đường" },
    category: "cocktail",
    basePortions: 1,
    ingredients: [
      ing("i1", "White sugar", "Đường trắng", 825, "g"),
      ing("i2", "Water", "Nước", 825, "ml"),
    ],
    steps: [
      step("s1", "Combine sugar and water in a pot.", "Cho đường và nước vào nồi."),
      step("s2", "Warm gently, stirring, until sugar fully dissolves — do not boil hard.", "Đun nhẹ, khuấy đều, đến khi đường tan hoàn toàn — không đun sôi mạnh."),
      step("s3", "Cool and bottle. Refrigerate.", "Để nguội và đóng chai. Bảo quản tủ lạnh."),
    ],
    notes: { en: "Fixed batch — makes ~1.5L. Used as a cocktail/mocktail premix ingredient.", vi: "Mẻ cố định — cho ra ~1.5L. Dùng làm nguyên liệu pha premix cocktail/mocktail." },
    updatedAt: NOW,
  },
  {
    id: "rc_ginger_syrup",
    name: { en: "Ginger Syrup", vi: "Si Rô Gừng" },
    category: "cocktail",
    basePortions: 1,
    ingredients: [
      ing("i1", "Ginger, sliced", "Gừng thái lát", 600, "g"),
      ing("i2", "White sugar", "Đường trắng", 637.5, "g"),
      ing("i3", "Water", "Nước", 1050, "ml"),
    ],
    steps: [
      step("s1", "Combine ginger and water, simmer 20–30 min.", "Cho gừng và nước vào, hầm 20–30 phút."),
      step("s2", "Strain out ginger, return liquid to the pot, add sugar.", "Lọc bỏ gừng, cho nước lại vào nồi, thêm đường."),
      step("s3", "Simmer until sugar fully dissolves, cool and bottle.", "Hầm đến khi đường tan hoàn toàn, để nguội và đóng chai."),
    ],
    notes: { en: "Fixed batch — makes ~1.5L. Base of the Jerk & Chill Ginger Fizz.", vi: "Mẻ cố định — cho ra ~1.5L. Thành phần chính của Jerk & Chill Ginger Fizz." },
    updatedAt: NOW,
  },
  {
    id: "rc_spiced_syrup",
    name: { en: "Spiced Syrup (Cinnamon-Allspice)", vi: "Si Rô Gia Vị (Quế-Đa Hương)" },
    category: "cocktail",
    basePortions: 1,
    ingredients: [
      ing("i1", "Cinnamon stick", "Quế cây", 22.5, "g"),
      ing("i2", "Whole allspice", "Đa hương nguyên hạt", 15, "g"),
      ing("i3", "White sugar", "Đường trắng", 750, "g"),
      ing("i4", "Water", "Nước", 975, "ml"),
    ],
    steps: [
      step("s1", "Combine cinnamon, allspice and water, simmer 15–20 min to infuse.", "Cho quế, đa hương và nước vào, hầm 15–20 phút để dậy mùi."),
      step("s2", "Strain out spices, return liquid to the pot, add sugar.", "Lọc bỏ gia vị, cho nước lại vào nồi, thêm đường."),
      step("s3", "Simmer until sugar fully dissolves, cool and bottle.", "Hầm đến khi đường tan hoàn toàn, để nguội và đóng chai."),
    ],
    notes: { en: "Fixed batch — makes ~1.5L. Base of the Spiced Pineapple Daiquiri.", vi: "Mẻ cố định — cho ra ~1.5L. Thành phần chính của Spiced Pineapple Daiquiri." },
    updatedAt: NOW,
  },
  {
    id: "rc_rum_punch",
    name: { en: "Classic Rum Punch", vi: "Rum Punch Cổ Điển" },
    category: "cocktail",
    basePortions: 12,
    ingredients: [
      ing("i1", "Orange juice", "Nước cam", 500, "ml"),
      ing("i2", "Pineapple juice", "Nước dứa", 500, "ml"),
      ing("i3", "Lime juice", "Nước cốt chanh", 187.5, "ml"),
      ing("i4", "Grenadine", "Si rô lựu (grenadine)", 187.5, "ml"),
      ing("i5", "Sugar Syrup", "Si rô đường", 125, "ml"),
    ],
    steps: [
      step("s1", "Combine all premix ingredients in a batch jar, refrigerate.", "Trộn tất cả nguyên liệu premix vào bình, để tủ lạnh."),
      step("s2", "Cocktail: 120ml premix + 30ml white rum over ice, garnish grated nutmeg and orange wheel.", "Cocktail: 120ml premix + 30ml rum trắng với đá, trang trí nhục đậu khấu bào và lát cam."),
      step("s3", "Mocktail: 120ml premix + 45ml soda over ice, garnish grated nutmeg and orange wheel.", "Mocktail: 120ml premix + 45ml soda với đá, trang trí nhục đậu khấu bào và lát cam."),
    ],
    costPerPortionVnd: 29805,
    notes: { en: "1.5L batch premix, yields ~12 serves. Rum/soda added per serve at time of pour, not in the batch.", vi: "Mẻ premix 1.5L, cho ra ~12 ly. Rum/soda thêm khi rót từng ly, không pha sẵn trong mẻ." },
    updatedAt: NOW,
  },
  {
    id: "rc_passionfruit_colada",
    name: { en: "Passionfruit Colada", vi: "Passionfruit Colada" },
    category: "cocktail",
    basePortions: 12,
    ingredients: [
      ing("i1", "Coconut cream", "Kem dừa", 650, "ml"),
      ing("i2", "Pineapple juice", "Nước dứa", 475, "ml"),
      ing("i3", "Passion fruit syrup", "Si rô chanh dây", 250, "ml"),
      ing("i4", "Lime juice", "Nước cốt chanh", 125, "ml"),
    ],
    steps: [
      step("s1", "Combine all premix ingredients in a batch jar, refrigerate.", "Trộn tất cả nguyên liệu premix vào bình, để tủ lạnh."),
      step("s2", "Cocktail: 120ml premix + 30ml white rum shaken with ice, garnish pineapple wedge.", "Cocktail: 120ml premix + 30ml rum trắng lắc với đá, trang trí miếng dứa."),
      step("s3", "Mocktail: 120ml premix + 45ml soda shaken with ice, garnish pineapple wedge.", "Mocktail: 120ml premix + 45ml soda lắc với đá, trang trí miếng dứa."),
    ],
    costPerPortionVnd: 32842,
    notes: { en: "1.5L batch premix, yields ~12 serves. Rum/soda added per serve at time of pour, not in the batch.", vi: "Mẻ premix 1.5L, cho ra ~12 ly. Rum/soda thêm khi rót từng ly, không pha sẵn trong mẻ." },
    updatedAt: NOW,
  },
  {
    id: "rc_ginger_fizz",
    name: { en: "Jerk & Chill Ginger Fizz", vi: "Jerk & Chill Ginger Fizz" },
    category: "cocktail",
    basePortions: 33,
    ingredients: [
      ing("i1", "Ginger Syrup", "Si rô gừng", 1150, "ml"),
      ing("i2", "Lime juice", "Nước cốt chanh", 350, "ml"),
    ],
    steps: [
      step("s1", "Combine concentrate ingredients in a batch jar, refrigerate.", "Trộn nguyên liệu cốt vào bình, để tủ lạnh."),
      step("s2", "Cocktail: 45ml concentrate + 30ml dark rum over ice, top with 90ml soda, garnish lime wheel and mint.", "Cocktail: 45ml cốt + 30ml rum đen với đá, thêm 90ml soda, trang trí lát chanh và bạc hà."),
      step("s3", "Mocktail: 45ml concentrate over ice, top with 135ml soda, garnish lime wheel and mint.", "Mocktail: 45ml cốt với đá, thêm 135ml soda, trang trí lát chanh và bạc hà."),
    ],
    costPerPortionVnd: 45547,
    notes: { en: "1.5L batch concentrate, yields ~33 serves. Rum/soda added per serve at time of pour, not in the batch.", vi: "Mẻ cốt 1.5L, cho ra ~33 ly. Rum/soda thêm khi rót từng ly, không pha sẵn trong mẻ." },
    updatedAt: NOW,
  },
  {
    id: "rc_pineapple_daiquiri",
    name: { en: "Spiced Pineapple Daiquiri", vi: "Spiced Pineapple Daiquiri" },
    category: "cocktail",
    basePortions: 12,
    ingredients: [
      ing("i1", "Pineapple juice", "Nước dứa", 875, "ml"),
      ing("i2", "Lime juice", "Nước cốt chanh", 312.5, "ml"),
      ing("i3", "Spiced Syrup", "Si rô gia vị", 312.5, "ml"),
    ],
    steps: [
      step("s1", "Combine all premix ingredients in a batch jar, refrigerate.", "Trộn tất cả nguyên liệu premix vào bình, để tủ lạnh."),
      step("s2", "Cocktail: 120ml premix + 30ml spiced rum shaken with ice, garnish pineapple leaf.", "Cocktail: 120ml premix + 30ml rum gia vị lắc với đá, trang trí lá dứa."),
      step("s3", "Mocktail: 120ml premix + 45ml soda shaken with ice, garnish pineapple leaf.", "Mocktail: 120ml premix + 45ml soda lắc với đá, trang trí lá dứa."),
    ],
    costPerPortionVnd: 48815,
    notes: { en: "1.5L batch premix, yields ~12 serves. Rum/soda added per serve at time of pour, not in the batch.", vi: "Mẻ premix 1.5L, cho ra ~12 ly. Rum/soda thêm khi rót từng ly, không pha sẵn trong mẻ." },
    updatedAt: NOW,
  },
];
