import { NextResponse } from "next/server";
import { exchangeAuthorizationCode } from "@/lib/zalo/tokens";
import { getZaloConfig } from "@/lib/zalo/config";
import { ZaloError } from "@/lib/zalo/errors";
import { configuredVerifier } from "@/lib/zalo/pkce";

/**
 * Receives Zalo's redirect and completes the connection.
 *
 * The authorization code is single-use and expires in ten minutes, so there is
 * no retry here — a failure sends the owner back to try again rather than
 * silently burning the code.
 */

export const runtime = "nodejs";

function done(request: Request, params: Record<string, string>) {
  const url = new URL("/settings/zalo", request.url);
  Object.entries(params).forEach(([k, v]) => url.searchParams.set(k, v));
  return NextResponse.redirect(url);
}

/**
 * Zalo verifies ownership of a URL prefix by fetching that exact URL and
 * looking for its verification meta tag. This route normally answers with a
 * redirect, which a crawler can't read a tag out of — so a bare GET, with no
 * query string at all, serves a minimal HTML page carrying the tag instead.
 *
 * Safe to distinguish this way: a real OAuth return always carries at least
 * `code` or `state`, so nothing with query parameters is ever treated as a
 * verification probe.
 */
const VERIFICATION_TOKEN = "KkI46RAL1nXiuhOKYySC7NxIkI6If6DuC30m";

function verificationPage(): Response {
  return new Response(
    `<!DOCTYPE html><html lang="en"><head><meta name="zalo-platform-site-verification" content="${VERIFICATION_TOKEN}" /></head><body>Jerk &amp; Chill — Zalo callback</body></html>`,
    { status: 200, headers: { "Content-Type": "text/html; charset=utf-8" } }
  );
}

export async function GET(request: Request) {
  const url = new URL(request.url);
  // No parameters at all — this is the ownership check, not a user coming back
  // from consent.
  if ([...url.searchParams.keys()].length === 0) return verificationPage();

  const cfg = getZaloConfig();
  if (!cfg) return done(request, { connected: "0", reason: "not_configured" });

  const code = url.searchParams.get("code");
  const oaId = url.searchParams.get("oa_id");

  // The verifier is fixed configuration, because the console holds a fixed
  // challenge. There is no per-request cookie to read any more — the consent
  // link is generated by Zalo, so nothing of ours starts the round trip.
  const verifier = configuredVerifier();

  if (!code) return done(request, { connected: "0", reason: "no_code" });
  // No state check: Zalo generates the consent link, so there is no nonce of
  // ours to compare against. The authorization code is single-use, expires in
  // ten minutes, and is worthless without the app secret — which is what
  // actually protects the exchange.
  if (!verifier) return done(request, { connected: "0", reason: "no_verifier" });

  // Zalo returns oa_id on the callback. When ZALO_OA_ID is configured it is
  // enforced — approving some other Official Account is a mistake worth
  // catching. When it isn't, this callback is how we learn which OA we have,
  // so there is nothing to compare against and the returned value is stored.
  if (cfg.oaId && oaId && oaId !== cfg.oaId) {
    return done(request, { connected: "0", reason: "wrong_oa" });
  }
  const effectiveOaId = oaId ?? cfg.oaId;
  if (!effectiveOaId) {
    return done(request, { connected: "0", reason: "no_oa_id" });
  }

  try {
    await exchangeAuthorizationCode(cfg, code, verifier, effectiveOaId);
    return done(request, { connected: "1" });
  } catch (err) {
    // Pass Zalo's own words through. Swallowing them into a generic
    // "exchange_failed" is how this became guesswork: the oauth endpoint's
    // -14xxx codes are published in no error table, so its message string is
    // the only real signal it gives.
    console.error("[zalo] token exchange failed", err);
    if (err instanceof ZaloError) {
      return done(request, {
        connected: "0",
        reason: "exchange_failed",
        code: String(err.code),
        detail: err.zaloMessage.slice(0, 200),
      });
    }
    return done(request, {
      connected: "0",
      reason: "exchange_failed",
      detail: (err instanceof Error ? err.message : String(err)).slice(0, 200),
    });
  }
}
